CREATE TABLE MUA (
County_State VARCHAR NOT NULL, 
Designation_Type VARCHAR NOT NULL,
Index_Score VARCHAR NOT NULL,
Status VARCHAR NOT NULL,
Rual_Status VARCHAR NOT NULL,
PRIMARY KEY (County_State)
);

CREATE TABLE Mortality (
County_State VARCHAR NOT NULL,
Cancer_Type VARCHAR NOT NULL,
Race VARCHAR NOT NULL,
Gender VARCHAR NOT NULL,
Age INT NOT NULL,
Mortality VARCHAR NOT NULL,
FOREIGN KEY (County_State) REFERENCES MUA (County_State),
PRIMARY KEY (County_State)
);

CREATE TABLE Incidence (
County_State VARCHAR NOT NULL,
Cancer_Type VARCHAR NOT NULL,
Race VARCHAR NOT NULL,
Gender VARCHAR NOT NULL,
Age INT NOT NULL,
Incidence VARCHAR NOT NULL,
FOREIGN KEY (County_State) REFERENCES MUA (County_State),
PRIMARY KEY (County_State)
);

SELECT * FROM MUA
SELECT * FROM Mortality
SELECT * FROM Incidence
